# Generated by Django 5.1.7 on 2025-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_experience_points_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_up_xp',
            field=models.IntegerField(default=10),
        ),
    ]
